name: ci
on:
  push:
    branches:
      - 'next'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: awharn
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        id:   build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            awharn/jenkins-nvm-zowe-cli:zowe-v2-lts
            ghcr.io/awharn/jenkins-nvm-zowe-cli:zowe-v2-lts
      
      - name: Image Digest
        run:  echo ${{ steps.build.outputs.digest }}
      
      - name: Update Downstream - Next
        uses: benc-uk/workflow-dispatch@v1
        with: 
          ref:      refs/heads/next
          workflow: ci
          repo:     awharn/jenkins-nvm-zowe-cli-extended
          token:    ${{ secrets.PAT }}